# Engine package metadata stored as Python.

PACKAGE = {'name': 'replit-opsgate-engine-foundation',
 'version': '6.0.30',
 'private': True,
 'type': 'module',
 'scripts': {'build': 'python3 tools/opsgate_tools.py build-distributions',
             'validate': 'python3 tools/opsgate_tools.py validate-engine',
             'compile:frontend': 'python3 tools/opsgate_tools.py compile-prompt routing:frontend-task',
             'state:migration': 'python3 tools/opsgate_tools.py init-state routing:migration-task-missing-auth',
             'parse:report': 'python3 tools/opsgate_tools.py parse-report fixtures/reports/sample-replit-final-report.md',
             'preflight': 'python3 tools/opsgate_tools.py preflight routing:frontend-task',
             'check:paths': 'python3 tools/opsgate_tools.py check-paths routing:frontend-task',
             'check:capabilities': 'python3 tools/opsgate_tools.py check-capabilities '
                                   'routing:migration-task-missing-auth',
             'lint:prompt': 'python3 tools/opsgate_tools.py lint-prompt fixtures/prompts/frontend-compiled-with-gate.md',
             'lint:report': 'python3 tools/opsgate_tools.py lint-report fixtures/reports/sample-replit-final-report.md',
             'audit:engine': 'python3 tools/opsgate_tools.py audit-engine dist/replit-install',
             'init:run': 'python3 tools/opsgate_tools.py init-run routing:frontend-task',
             'intake': 'python3 tools/opsgate_tools.py intake-request',
             'next-phase': 'python3 tools/opsgate_tools.py next-phase-prompt state:ready-phased-state reports:parsed-sample-report',
             'install:replit': 'python3 tools/opsgate_tools.py build-replit-install',
             'release-notes': 'python3 tools/opsgate_tools.py release-notes',
             'route:frontend': 'python3 tools/opsgate_tools.py route-request routing:frontend-task',
             'route:migration': 'python3 tools/opsgate_tools.py route-request routing:migration-task-missing-auth'}}
