# Engine package metadata stored as Python.

PACKAGE = {'name': 'replit-opsgate-engine-foundation',
 'version': '6.0.16',
 'private': True,
 'type': 'module',
 'scripts': {'build': 'python3 tools/build-distributions.py',
             'validate': 'python3 tools/validate-kit.py',
             'compile:frontend': 'python3 tools/compile-prompt.py routing:frontend-task',
             'state:migration': 'python3 tools/init-state.py routing:migration-task-missing-auth',
             'parse:report': 'python3 tools/parse-report.py fixtures/reports/sample-replit-final-report.md',
             'preflight': 'python3 tools/preflight.py routing:frontend-task',
             'check:paths': 'python3 tools/check-paths.py routing:frontend-task',
             'check:capabilities': 'python3 tools/check-capabilities.py '
                                   'routing:migration-task-missing-auth',
             'lint:prompt': 'python3 tools/lint-prompt.py fixtures/prompts/frontend-compiled-with-gate.md',
             'lint:report': 'python3 tools/lint-report.py fixtures/reports/sample-replit-final-report.md',
             'audit:engine': 'python3 tools/audit-engine.py dist/replit-install',
             'init:run': 'python3 tools/init-run.py routing:frontend-task',
             'intake': 'python3 tools/intake-request.py',
             'next-phase': 'python3 tools/next-phase-prompt.py state:ready-phased-state reports:parsed-sample-report',
             'install:replit': 'python3 tools/build-replit-install.py',
             'release-notes': 'python3 tools/release-notes.py',
             'route:frontend': 'python3 tools/route-request.py routing:frontend-task',
             'route:migration': 'python3 tools/route-request.py routing:migration-task-missing-auth'}}
