#!/usr/bin/env python3
"""Materialize a project's real replit.md, ai/**, and opsgate.profile.json from a filled-in
PROJECT_SETUP.md - the tool the Agent-driven first-run setup flow in
canonical/references/replit.md's "First-run setup check" runs once a human has answered the
template's fields. This is the primary onboarding path for a new project: the Agent asks the
user plain-language questions and writes the answers into the template itself - the user is
never expected to edit PROJECT_SETUP.md directly - and everything downstream from that filled-in
file - the profile config, the business file, and the literal configuration summary baked into
replit.md itself - is generated by this tool. (tools/init-profile.py is the lower-level, flags-only primitive this shares its actual
file-writing logic with - see tools/opsgate_setup_lib.py - for scripted/CI use instead of a
template.)

Writes, all under --target-root (the outer/consuming project's own root, never inside this
engine):

  <target-root>/opsgate.profile.json  - profile + protected-path config (shared logic with
                                         tools/init-profile.py).
  <target-root>/ai/<profile>.md       - business file, with the template's Business Facts
                                         answers written directly into it - not left as
                                         placeholders, since the Agent already collected them from the user.
  <target-root>/ai/*.md               - the engine's generic domain files (backend.md,
                                         frontend.md, etc.), copied over if not already present -
                                         these apply to any project and need no project-specific
                                         filling in.
  <target-root>/replit.md             - a copy of the engine's canonical replit.md with the
                                         "This project's configuration" placeholder replaced by
                                         a literal summary of this project's actual roots and
                                         protected paths - not just a reference to look them up
                                         dynamically.

Usage:
  python3 tools/apply-setup.py --template PROJECT_SETUP.md --target-root .
"""
import argparse
import re
import sys
from pathlib import Path

import opsgate_setup_lib as lib

ENGINE_ROOT = Path(__file__).resolve().parent.parent

FIELD_RE = re.compile(r"<!--\s*key:\s*(\w+)\s*-->\s*\n(.*?)(?=\n#{1,6}\s|\Z)", re.DOTALL)
CONFIG_SUMMARY_RE = re.compile(
    r"(<!-- OPSGATE:CONFIG_SUMMARY:START -->\n).*?(\n<!-- OPSGATE:CONFIG_SUMMARY:END -->)", re.DOTALL
)

BUSINESS_FIELD_BULLETS = [
    ("business_source", "Source", "none yet - fill in as decisions are made"),
    ("business_roles", "Roles", "not yet defined"),
    ("business_lifecycle", "Lifecycle", "not yet defined"),
    ("business_id_formats", "ID formats", "not yet defined"),
    ("business_rules", "Key business rules", "not yet defined"),
    ("business_design_system", "Design system", "not yet defined"),
    ("business_known_drift", "Known drift to watch for", "none known yet"),
]


def parse_args(argv):
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--template", required=True, help="path to the filled-in PROJECT_SETUP.md")
    p.add_argument(
        "--target-root",
        default=None,
        help="the outer project's own root - NOT this engine's directory. Defaults to the "
        "template file's own directory, since the template normally lives at the project root.",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="overwrite an existing business file, and re-copy generic ai/**  files that already exist",
    )
    return p.parse_args(argv)


def clean_field(raw):
    text = raw.strip()
    if not text or text.startswith("[FILL IN"):
        return None
    return text


def parse_template(template_path):
    text = template_path.read_text(encoding="utf-8")
    return {match.group(1): clean_field(match.group(2)) for match in FIELD_RE.finditer(text)}


def require(fields, key, human_label):
    value = fields.get(key)
    if not value:
        lib.fail(f"{human_label!r} is still unfilled in the template (key: {key}) - fill it in before running setup.")
    return value


def split_globs(raw):
    if not raw:
        return []
    return [part.strip() for part in re.split(r"[,\n]+", raw) if part.strip()]


def render_business_facts_block(fields):
    lines = [f"- {label}: {fields.get(key) or default}" for key, label, default in BUSINESS_FIELD_BULLETS]
    return "\n".join(lines)


def render_one_profile_summary(profile, entry):
    frontend = f"`{entry.get('frontend_root')}`" if entry.get("frontend_root") else "_none_"
    backend = f"`{entry.get('backend_root')}`" if entry.get("backend_root") else "_none_"
    extra = entry.get("extra_never_access") or []
    protected = ", ".join(f"`{g}`" for g in extra) if extra else "_none_"
    return (
        f"- Profile: `{profile}`\n"
        f"  - Frontend root: {frontend}\n"
        f"  - Backend root: {backend}\n"
        f"  - Protected paths (in addition to the universal baseline): {protected}\n"
        f"  - Business file: `{entry.get('business_file')}`"
    )


def render_config_summary(all_profiles):
    """Render every profile currently in opsgate.profile.json, not just the one just added -
    re-running setup for a second profile must not silently erase the first one's summary from
    replit.md, even though opsgate.profile.json itself already correctly holds both."""
    if not all_profiles:
        return "_Not yet configured - see \"First-run setup check\" above._"
    return "\n".join(render_one_profile_summary(key, entry) for key, entry in all_profiles.items())


def materialize_replit_md(target_root, all_profiles):
    source = ENGINE_ROOT / "canonical" / "references" / "replit.md"
    text = source.read_text(encoding="utf-8")
    summary = render_config_summary(all_profiles)
    new_text, count = CONFIG_SUMMARY_RE.subn(lambda m: m.group(1) + summary + m.group(2), text, count=1)
    if count != 1:
        lib.fail(
            "could not find the OPSGATE:CONFIG_SUMMARY markers in the engine's canonical replit.md - "
            "has it changed shape? Copy it over and fill the summary in by hand instead."
        )
    dest = target_root / "replit.md"
    dest.write_text(new_text, encoding="utf-8")
    return dest


def copy_generic_ai_files(target_root, force):
    source_dir = ENGINE_ROOT / "canonical" / "references" / "ai"
    dest_dir = target_root / "ai"
    dest_dir.mkdir(parents=True, exist_ok=True)
    copied, skipped = [], []
    for item in sorted(source_dir.glob("*.md")):
        if item.stem == "metco":
            # ai/metco.md is METCO's own project-specific business file, still legacy-built
            # into this engine (see canonical/README-v6.md's "Known migration debt") - it is
            # not a generic domain file and must never be copied into another project.
            continue
        dest = dest_dir / item.name
        if dest.exists() and not force:
            skipped.append(dest)
            continue
        dest.write_text(item.read_text(encoding="utf-8"), encoding="utf-8")
        copied.append(dest)
    return copied, skipped


def main(argv):
    args = parse_args(argv)
    template_path = Path(args.template).expanduser().resolve()
    if not template_path.exists():
        lib.fail(f"--template {args.template!r} does not exist.")

    fields = parse_template(template_path)
    profile = require(fields, "profile", "Profile key")
    lib.validate_profile_key(profile)
    project_name = require(fields, "project_name", "Project name")

    target_root = Path(args.target_root).expanduser().resolve() if args.target_root else template_path.parent
    if not target_root.is_dir():
        lib.fail(f"--target-root {args.target_root!r} is not an existing directory.")

    entry = lib.build_entry(
        profile,
        frontend_root=fields.get("frontend_root"),
        backend_root=fields.get("backend_root"),
        description=f"{project_name} Replit project profile. Select explicitly "
        f"(OPSGATE_PROFILE={profile} or request.profile).",
        extra_never_access=split_globs(fields.get("extra_never_access")),
    )
    business_facts_block = render_business_facts_block(fields)
    config_path, business_file_path = lib.write_profile(
        target_root, profile, entry, business_facts_block=business_facts_block, force=args.force
    )
    all_profiles = lib.load_config(config_path)["profiles"]
    replit_md_path = materialize_replit_md(target_root, all_profiles)
    copied, skipped = copy_generic_ai_files(target_root, args.force)

    print(f"Set up {project_name!r} as profile {profile!r}:")
    print(f"  {config_path}")
    print(f"  {business_file_path} (Business Facts filled in from the template)")
    print(f"  {replit_md_path} (configuration summary filled in - re-read this file before continuing)")
    if copied:
        print(f"  copied {len(copied)} generic ai/**  file(s): {', '.join(p.name for p in copied)}")
    if skipped:
        print(f"  left {len(skipped)} existing ai/**  file(s) unchanged (pass --force to overwrite): "
              f"{', '.join(p.name for p in skipped)}")
    print()
    print("Next steps:")
    print(f"  1. Set OPSGATE_PROFILE={profile} (a Repl Secret is the usual place).")
    print(f"  2. Re-read {replit_md_path} - it replaces the generic copy this setup ran from.")
    print("  3. Nothing in this engine's own repo needs to change or be rebuilt.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
