# Generated METCO Python contracts. Edit this file instead of standalone JSON manifests.

KIT_MANIFEST = {'name': 'metco-kit',
 'version': '6.0.13',
 'release_date': '2026-08-10',
 'source_version': '6',
 'purpose': 'Canonical METCO prompt, skill, and Replit engine foundation kit with object-oriented instruction '
            'contracts.',
 'canonical_root': 'canonical',
 'generated_roots': ['dist/claude', 'dist/replit'],
 'commands': {'validate': 'python3 tools/validate-kit.py',
              'test_all': 'python3 tools/test-all.py',
              'build': 'python3 tools/build-distributions.py',
              'route': 'python3 tools/route-request.py <request.json>',
              'compile': 'python3 tools/compile-prompt.py <request.json>',
              'init_state': 'python3 tools/init-state.py <request.json>',
              'parse_report': 'python3 tools/parse-report.py <report.md>',
              'diff_upgrade': 'python3 tools/diff-upgrade.py <old-kit-root> [new-kit-root]',
              'intake': 'python3 tools/intake-request.py "<plain language request>"',
              'next_phase': 'python3 tools/next-phase-prompt.py <run-state.json> <parsed-report.json>',
              'replit_install': 'python3 tools/build-replit-install.py',
              'release_notes': 'python3 tools/release-notes.py [old-kit-root]',
              'preflight': 'python3 tools/preflight.py <request.json>',
              'check_paths': 'python3 tools/check-paths.py <request.json>',
              'check_capabilities': 'python3 tools/check-capabilities.py <request.json>',
              'lint_prompt': 'python3 tools/lint-prompt.py <prompt.md>',
              'lint_report': 'python3 tools/lint-report.py <report.md>',
              'audit_engine': 'python3 tools/audit-engine.py [project-root]',
              'init_run': 'python3 tools/init-run.py <request.json>',
              'record_decision': 'python3 tools/record-decision.py <HITL-ID> <answer and exact scope>',
              'show_profile': 'python3 tools/show-profile.py [request.json]'},
 'release_acceptance': ['canonical distribution mappings pass',
                        'Replit skill metadata is valid',
                        'protected path rules remain present',
                        'HITL is limited to three cases',
                        'generated archives pass integrity checks',
                        'routing fixtures produce expected outcomes',
                        'canonical AI instruction objects expose responsibility, activation, inputs, boundaries, '
                        'workflow, and output evidence']}

ROUTING_MANIFEST = {'artifact_routes': [{'deliverable': 'business_file',
                      'mode': 'BUSINESS_DEFINITION',
                      'template': 'templates/METCO_BUSINESS_FILE_PROMPT_TEMPLATE.md',
                      'signals': ['business', 'scope', 'rules', 'outcomes', 'stakeholders', 'module audit']},
                     {'deliverable': 'specification',
                      'mode': 'IMPLEMENTATION_SPECIFICATION',
                      'template': 'templates/METCO_SPEC_FILE_PROMPT_TEMPLATE.md',
                      'signals': ['specification', 'contracts', 'states', 'data', 'delta spec']},
                     {'deliverable': 'audit',
                      'mode': 'EVIDENCE_AUDIT',
                      'template': 'templates/METCO_AUDIT_PROMPT_TEMPLATE.md',
                      'signals': ['audit', 'review', 'findings', 'compliance', 'risk']},
                     {'deliverable': 'task_backlog',
                      'mode': 'DELIVERY_BACKLOG',
                      'template': 'templates/METCO_TASK_BACKLOG_PROMPT_TEMPLATE.md',
                      'signals': ['backlog', 'tasks', 'delivery plan']},
                     {'deliverable': 'change_record',
                      'mode': 'CHANGE_CONTROL',
                      'template': 'templates/METCO_CHANGE_IMPROVEMENT_PROMPT_TEMPLATE.md',
                      'signals': ['change', 'improvement', 'amendment']},
                     {'deliverable': 'replit_prompt',
                      'mode': 'REPLIT_PROMPT_BUILD',
                      'template': 'templates/METCO_REPLIT_TASK_TEMPLATE.md',
                      'signals': ['implement', 'fix', 'build', 'replit prompt']}],
 'replit_routes': [{'mode': 'AUTH_PERMISSION_IMPLEMENTATION',
                    'skill': 'metco-auth-permission-workflow',
                    'signals': ['auth',
                                'permission',
                                'permissions',
                                'changes permissions',
                                'role',
                                'role-based',
                                'tenant',
                                'object scope',
                                'sensitive field',
                                'authorization'],
                    'references': ['ai/metco.md',
                                   'ai/backend.md',
                                   'ai/database.md',
                                   'ai/security.md',
                                   'ai/frontend.md',
                                   'ai/testing.md']},
                   {'mode': 'DATABASE_SCHEMA_EVOLUTION',
                    'skill': 'metco-database-schema-migration',
                    'signals': ['schema', 'migration', 'backfill', 'mapping', 'index'],
                    'capability': 'schema_migration_backfill',
                    'force_phased': True,
                    'references': ['ai/metco.md',
                                   'ai/database.md',
                                   'ai/backend.md',
                                   'ai/security.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'NONPRODUCTION_DATA_SEEDING',
                    'skill': 'metco-data-seeding',
                    'signals': ['seed', 'seeding', 'demo data', 'test data'],
                    'capability': 'data_seeding',
                    'force_phased': True,
                    'references': ['ai/metco.md',
                                   'ai/database.md',
                                   'ai/backend.md',
                                   'ai/security.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'FORM_WORKFLOW_IMPLEMENTATION',
                    'skill': 'metco-form-workflow',
                    'signals': ['form', 'validation', 'save', 'cancel', 'mutation'],
                    'references': ['ai/metco.md', 'ai/frontend.md', 'ai/ui-ux.md', 'ai/testing.md']},
                   {'mode': 'TABLE_REPORTING_IMPLEMENTATION',
                    'skill': 'metco-table-reporting-workflow',
                    'signals': ['table', 'filter', 'sort', 'pagination', 'report', 'dashboard'],
                    'references': ['ai/metco.md',
                                   'ai/frontend.md',
                                   'ai/ui-ux.md',
                                   'ai/testing.md',
                                   'ai/backend.md',
                                   'ai/database.md',
                                   'ai/security.md']},
                   {'mode': 'FRONTEND_ARCHITECTURE_REFACTOR',
                    'skill': 'metco-frontend-architecture-refactor',
                    'signals': ['refactor', 'consolidate', 'decompose', 'duplicate component'],
                    'capability': 'broad_architecture_refactor',
                    'force_phased': True,
                    'references': ['ai/metco.md',
                                   'ai/frontend.md',
                                   'ai/refactoring.md',
                                   'ai/ui-ux.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'PERFORMANCE_OPTIMIZATION',
                    'skill': 'metco-performance-optimization',
                    'signals': ['performance', 'slow', 'latency', 'render', 'n+1', 'payload'],
                    'references': ['ai/metco.md',
                                   'ai/testing.md',
                                   'ai/frontend.md',
                                   'ai/backend.md',
                                   'ai/database.md']},
                   {'mode': 'UI_UX_REVIEW',
                    'skill': 'metco-ui-ux-review',
                    'signals': ['ui', 'ux', 'responsive', 'accessibility', 'visual'],
                    'references': ['ai/metco.md', 'ai/ui-ux.md', 'ai/testing.md']},
                   {'mode': 'BUG_DIAGNOSIS',
                    'skill': 'metco-bug-diagnosis',
                    'signals': ['bug', 'diagnose', 'root cause', 'reproduce'],
                    'references': ['ai/metco.md', 'ai/testing.md']},
                   {'mode': 'FULL_STACK_IMPLEMENTATION',
                    'skill': 'metco-full-stack-feature',
                    'signals': ['frontend and backend', 'full stack', 'api and ui'],
                    'force_phased_when_risky': True,
                    'references': ['ai/metco.md',
                                   'ai/backend.md',
                                   'ai/database.md',
                                   'ai/security.md',
                                   'ai/frontend.md',
                                   'ai/ui-ux.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'API_IMPLEMENTATION',
                    'skill': 'metco-api-server-development',
                    'signals': ['api', 'endpoint', 'service', 'repository', 'backend'],
                    'references': ['ai/metco.md', 'ai/backend.md', 'ai/testing.md']},
                   {'mode': 'FRONTEND_IMPLEMENTATION',
                    'skill': 'metco-frontend-development',
                    'signals': ['frontend', 'react', 'component', 'page', 'hook', 'client'],
                    'references': ['ai/metco.md', 'ai/frontend.md', 'ai/ui-ux.md', 'ai/testing.md']},
                   {'mode': 'SAFE_VERIFICATION',
                    'skill': 'metco-safe-verification',
                    'signals': ['verify', 'qa', 'regression', 'read-only'],
                    'references': ['ai/metco.md', 'ai/testing.md']},
                   {'mode': 'INSTRUCTION_SYSTEM_MAINTENANCE',
                    'skill': 'metco-instruction-maintenance',
                    'signals': ['replit.md', 'ai instructions', '.agents/skills', 'instruction'],
                    'capability': 'instruction_maintenance',
                    'references': ['ai/metco.md', 'ai/maintenance.md']}],
 'phased_triggers': ['schema',
                     'migration',
                     'backfill',
                     'seeding',
                     'authentication',
                     'tenant',
                     'sensitive data',
                     'public contract',
                     'broad refactor',
                     'destructive cleanup',
                     'multiple independently reversible surfaces']}

CAPABILITY_GATES = {'ordinary_application_change': {'default': 'allowed_when_scoped',
                                 'requires': ['observable_outcome', 'exact_scope_inside_normal_write_paths']},
 'audit_or_diagnosis_without_fixes': {'default': 'read_only', 'requires': ['approved_inspection_scope']},
 'broad_architecture_refactor': {'default': 'blocked',
                                 'requires': ['explicit_broad_outcome',
                                              'named_approved_source_tree',
                                              'preserved_contracts',
                                              'phased_rollback']},
 'instruction_maintenance': {'default': 'blocked',
                             'requires': ['explicit_instruction_change_request', 'exact_instruction_paths']},
 'schema_migration_backfill': {'default': 'blocked',
                               'requires': ['explicit_schema_or_migration_request',
                                            'approved_target_mapping',
                                            'named_established_paths',
                                            'safe_non_production_environment',
                                            'rollback_plan']},
 'data_seeding': {'default': 'blocked',
                  'requires': ['explicit_seeding_request',
                               'named_established_seed_paths',
                               'safe_non_production_environment',
                               'approved_profiles_and_scale',
                               'idempotency']},
 'contract_change_or_destructive_cleanup': {'default': 'blocked',
                                            'requires': ['explicit_changed_boundary',
                                                         'consumer_evidence',
                                                         'compatibility_plan',
                                                         'recovery_plan']},
 'package_config_environment_deployment': {'default': 'blocked',
                                           'requires': ['exact_explicit_authorization',
                                                        'task_specific_safety_prerequisites']}}

# Protections every profile gets regardless of which specific project the kit is running
# against - these are universal engineering risks (VCS internals, secrets files, dependency
# trees, CI, agent memory), not anything specific to the METCO project. A brand-new Replit
# project that only sets METCO_PROFILE=generic-replit still gets this baseline for free instead
# of an empty or missing protected-path list.
_UNIVERSAL_NEVER_ACCESS = ['.git/**', '.env', '.env.*', 'node_modules/**', '.github/workflows/**', '.claude/**', '.agents/memory/**']
# Locked-by-default categories are already project-agnostic (packages, lockfiles, schema,
# secrets, etc. are universal engineering categories, not METCO-specific paths), so both
# profiles below share the exact same list rather than each declaring their own copy.
_UNIVERSAL_LOCKED_BY_DEFAULT = ['packages',
                               'lockfiles',
                               'dependencies',
                               'workspace_config',
                               'build_lint_format_config',
                               '.replit',
                               'environment',
                               'secrets',
                               'deployment',
                               'infrastructure',
                               'generated_contracts',
                               'schema',
                               'migrations',
                               'seeds',
                               '.agents/memory/**',
                               'instructions',
                               'unrelated_docs']

PROTECTED_PATHS = {'profiles': {'metco': {'normal_write_paths': ['artifacts/metco/src/**', 'artifacts/api-server/src/**'],
                        # metco-api/** and pipeline/** are this project's own protected trees -
                        # kept only on the metco profile, not the universal baseline, since they
                        # would be meaningless (and misleadingly specific) noise on any other
                        # project that adopts this kit via the generic-replit profile.
                        'never_access': [*_UNIVERSAL_NEVER_ACCESS, 'metco-api/**', 'pipeline/**', '**/metco-api/**', '**/pipeline/**'],
                        'locked_by_default': list(_UNIVERSAL_LOCKED_BY_DEFAULT)},
                    'generic-replit': {'normal_write_paths': [],
                        'never_access': list(_UNIVERSAL_NEVER_ACCESS),
                        'locked_by_default': list(_UNIVERSAL_LOCKED_BY_DEFAULT)}}}

HITL_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'METCO HITL Decision',
 'type': 'object',
 'required': ['id',
              'case',
              'blocked_step',
              'question',
              'evidence_checked',
              'options',
              'exact_resume_point',
              'resume_reply'],
 'properties': {'id': {'type': 'string', 'pattern': '^HITL-[A-Za-z0-9-]+(-P[0-9]+)?-Q[0-9]+$'},
                'case': {'type': 'integer', 'enum': [1, 2, 3]},
                'blocked_step': {'type': 'string', 'minLength': 1},
                'question': {'type': 'string', 'minLength': 1},
                'evidence_checked': {'type': 'array', 'items': {'type': 'string'}, 'minItems': 1},
                'options': {'type': 'array', 'items': {'type': 'string', 'minLength': 1}, 'minItems': 2, 'maxItems': 4},
                'exact_resume_point': {'type': 'string', 'minLength': 1},
                'resume_reply': {'type': 'string', 'pattern': '^DECIDE HITL-[A-Za-z0-9-]+(-P[0-9]+)?-Q[0-9]+: .+'}}}

REQUEST_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'METCO Engine Request',
 'type': 'object',
 'required': ['id', 'outcome', 'deliverable'],
 'properties': {'id': {'type': 'string'},
                'outcome': {'type': 'string'},
                'deliverable': {'type': 'string',
                                'enum': ['business_file',
                                         'specification',
                                         'audit',
                                         'task_backlog',
                                         'change_record',
                                         'replit_prompt']},
                'module': {'type': 'string'},
                'scope': {'type': 'object',
                          'properties': {'write_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'read_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'locked_paths': {'type': 'array', 'items': {'type': 'string'}}}},
                'authorizations': {'type': 'object',
                                   'additionalProperties': {'type': 'object',
                                                            'properties': {'authorized': {'type': 'boolean'},
                                                                           'evidence': {'type': 'array',
                                                                                        'items': {'type': 'string'}}}}},
                'acceptance': {'type': 'array', 'items': {'type': 'string'}},
                'must_not_change': {'type': 'array', 'items': {'type': 'string'}},
                # Optional speed-oriented fields for replit_prompt requests - all opt-in, and
                # each is a no-op when absent so existing requests compile byte-identical prompts.
                'mcp': {'type': 'object',
                       'description': 'When enabled, compile-prompt.py emits MCP tool-call instructions (metco_preflight/check_paths/check_capability/record_decision) for the HITL gate instead of a manual prose reasoning table, since the target project has those tools registered on /mcp.',
                       'properties': {'enabled': {'type': 'boolean'},
                                      'tool_prefix': {'type': 'string', 'description': 'Defaults to "metco_" - override only if the target server registered the kit tools under a different prefix.'}}},
                'known_context': {'type': 'object',
                                  'description': 'When any of these are set, compile-prompt.py replaces the open-ended discovery steps with a targeted verification instruction against the named items instead of telling the agent to go find them.',
                                  'properties': {'owners': {'type': 'array', 'items': {'type': 'string'}},
                                                 'callers': {'type': 'array', 'items': {'type': 'string'}},
                                                 'tests': {'type': 'array', 'items': {'type': 'string'}}}},
                'reference_scope': {'type': 'string',
                                    'enum': ['full', 'minimal'],
                                    'description': 'Defaults to "full" (unchanged behavior). "minimal" trims required_references down to only the ones whose topic keywords appear in the request text/scope, always keeping replit.md and ai/metco.md.'},
                'profile': {'type': 'string',
                           'description': 'Which PROFILES entry (protected paths, write roots) governs this request. Defaults to the METCO_PROFILE environment variable if set, then manifests/profiles.json default_profile ("metco"), then "generic-replit" if neither resolves to a known profile. Set this (or METCO_PROFILE) to "generic-replit" when this kit is dropped into a project other than the one it was built for.'}}}

DISTRIBUTIONS = {'claude': {'root': 'dist/claude',
             'copies': [['canonical/CLAUDE_PROJECT_INSTRUCTIONS.md', 'dist/claude/CLAUDE_PROJECT_INSTRUCTIONS.md'],
                        ['canonical/templates', 'dist/claude/templates'],
                        ['canonical/references', 'dist/claude/references'],
                        ['canonical/specifications', 'dist/claude/specifications'],
                        ['canonical/examples', 'dist/claude/examples']],
             'skill_packages': ['metco-project-prompt-router', 'metco-replit-task-builder', 'metco-kit-maintainer', 'metco-mcp-integration'],
             # Sources copied into dist/claude/claude-skill/<target>. Shared by build-distributions.py
             # (which writes these) and validate-kit.py (which checks canonical/dist byte-identity),
             # so this is the single source of truth for the skill-package reference copy map.
             'skill_reference_mappings': [
                 ['canonical/templates/METCO_REPLIT_PHASED_IMPLEMENTATION_TEMPLATE.md', 'metco-replit-task-builder/references/phased-implementation-template.md'],
                 ['canonical/references/replit.md', 'metco-replit-task-builder/references/replit.md'],
                 ['canonical/templates/METCO_PROMPT_REQUEST_FORM.md', 'metco-replit-task-builder/references/request-form.md'],
                 ['canonical/examples/BACKEND_SEEDING_PROMPT_EXAMPLE.md', 'metco-replit-task-builder/references/example-backend-seeding.md'],
                 ['canonical/templates/METCO_HITL_DECISION_TEMPLATE.md', 'metco-replit-task-builder/references/hitl-decision-template.md'],
                 ['canonical/specifications/REPLIT_EXECUTION_SPEC.md', 'metco-replit-task-builder/references/replit-execution-spec.md'],
                 ['canonical/specifications/SCENARIO_SKILL_CONTRACTS_SPEC.md', 'metco-replit-task-builder/references/scenario-skill-contracts-spec.md'],
                 ['canonical/specifications/ENGINE_FOUNDATION_SPEC.md', 'metco-replit-task-builder/references/engine-foundation-spec.md'],
                 ['canonical/specifications/OBJECT_ORIENTED_INSTRUCTIONS_SPEC.md', 'metco-replit-task-builder/references/object-oriented-instructions-spec.md'],
                 ['canonical/templates/METCO_REPLIT_TASK_TEMPLATE.md', 'metco-replit-task-builder/references/task-template.md'],
                 ['canonical/specifications/PROCESS_MODES_SPEC.md', 'metco-replit-task-builder/references/process-modes-spec.md'],
                 ['canonical/specifications/HITL_SPEC.md', 'metco-replit-task-builder/references/hitl-spec.md'],
                 ['canonical/references/ai', 'metco-replit-task-builder/references/ai'],
                 ['canonical/references/replit-skills', 'metco-replit-task-builder/references/replit-skills'],
                 ['canonical/templates/METCO_REPLIT_PHASED_IMPLEMENTATION_TEMPLATE.md', 'metco-project-prompt-router/references/phased-implementation-template.md'],
                 ['canonical/references/replit.md', 'metco-project-prompt-router/references/replit.md'],
                 ['canonical/templates/METCO_PROMPT_REQUEST_FORM.md', 'metco-project-prompt-router/references/request-form.md'],
                 ['canonical/templates/METCO_BUSINESS_FILE_PROMPT_TEMPLATE.md', 'metco-project-prompt-router/references/business-file-template.md'],
                 ['canonical/templates/METCO_CHANGE_IMPROVEMENT_PROMPT_TEMPLATE.md', 'metco-project-prompt-router/references/change-improvement-template.md'],
                 ['canonical/templates/METCO_TASK_BACKLOG_PROMPT_TEMPLATE.md', 'metco-project-prompt-router/references/task-backlog-template.md'],
                 ['canonical/templates/METCO_HITL_DECISION_TEMPLATE.md', 'metco-project-prompt-router/references/hitl-decision-template.md'],
                 ['canonical/specifications/SKILL_ROUTING_SPEC.md', 'metco-project-prompt-router/references/routing-spec.md'],
                 ['canonical/specifications/OBJECT_ORIENTED_INSTRUCTIONS_SPEC.md', 'metco-project-prompt-router/references/object-oriented-instructions-spec.md'],
                 ['canonical/templates/METCO_AUDIT_PROMPT_TEMPLATE.md', 'metco-project-prompt-router/references/audit-template.md'],
                 ['canonical/specifications/ARTIFACT_CONTRACTS_SPEC.md', 'metco-project-prompt-router/references/artifact-contracts-spec.md'],
                 ['canonical/templates/METCO_SPEC_FILE_PROMPT_TEMPLATE.md', 'metco-project-prompt-router/references/spec-file-template.md'],
                 ['canonical/templates/METCO_REPLIT_TASK_TEMPLATE.md', 'metco-project-prompt-router/references/replit-task-template.md'],
                 ['canonical/specifications/PROCESS_MODES_SPEC.md', 'metco-project-prompt-router/references/process-modes-spec.md'],
             ]},
 'replit': {'root': 'dist/replit',
            'copies': [['canonical/references/replit.md', 'dist/replit/replit.md'],
                       ['canonical/references/ai', 'dist/replit/ai'],
                       ['canonical/references/replit-skills', 'dist/replit/.agents/skills']]}}

# default_profile is generic-replit, not metco: this engine is meant to be reused across
# whichever Replit project a submodule of it gets dropped into, and METCO is one specific
# project that happens to use it - not the engine's own identity. The one project that
# actually is METCO must opt in explicitly (METCO_PROFILE=metco, or a "profile" field on the
# request) rather than every other adopting project needing to opt out.
PROFILES = {'default_profile': 'generic-replit',
 'profiles': {'metco': {'description': 'METCO Replit frontend and Replit-backend project profile. Select explicitly (METCO_PROFILE=metco or request.profile) - it is no longer the default.',
                        'frontend_root': 'artifacts/metco/src',
                        'backend_root': 'artifacts/api-server/src',
                        'protected_policy': 'metco',
                        'test_policy': 'risk_based_existing_scripts_only',
                        'distribution': 'replit'},
              'generic-replit': {'description': "Default profile for any Replit project this kit is dropped into. frontend_root/backend_root are left unset (None) rather than guessed, since assuming a wrong folder name silently is worse than admitting it is not yet configured - set them by adding a project-specific profile (see canonical/README-v6.md) once the project's real roots are known.",
                                 'frontend_root': None,
                                 'backend_root': None,
                                 'protected_policy': 'project_defined',
                                 'test_policy': 'risk_based_existing_scripts_only',
                                 'distribution': 'replit'}}}

TEMPLATE_METADATA = {'templates/METCO_REPLIT_TASK_TEMPLATE.md': {'kind': 'replit_bounded_prompt',
                                             'required_fields': ['outcome', 'scope.write_paths', 'acceptance'],
                                             'optional_fields': ['module',
                                                                 'scope.read_paths',
                                                                 'must_not_change',
                                                                 'authorizations'],
                                             'final_output_policy': 'no_unresolved_placeholders'},
 'templates/METCO_REPLIT_PHASED_IMPLEMENTATION_TEMPLATE.md': {'kind': 'replit_phased_prompt',
                                                              'required_fields': ['outcome',
                                                                                  'scope.write_paths',
                                                                                  'acceptance'],
                                                              'optional_fields': ['module',
                                                                                  'scope.read_paths',
                                                                                  'must_not_change',
                                                                                  'authorizations'],
                                                              'final_output_policy': 'phase_plan_plus_next_authorized_phase_only'},
 'templates/METCO_BUSINESS_FILE_PROMPT_TEMPLATE.md': {'kind': 'business_artifact_prompt',
                                                      'required_fields': ['outcome'],
                                                      'optional_fields': ['module', 'acceptance', 'must_not_change'],
                                                      'final_output_policy': 'polished_artifact_prompt'},
 'templates/METCO_SPEC_FILE_PROMPT_TEMPLATE.md': {'kind': 'specification_artifact_prompt',
                                                  'required_fields': ['outcome'],
                                                  'optional_fields': ['module', 'acceptance', 'must_not_change'],
                                                  'final_output_policy': 'polished_artifact_prompt'},
 'templates/METCO_AUDIT_PROMPT_TEMPLATE.md': {'kind': 'audit_artifact_prompt',
                                              'required_fields': ['outcome'],
                                              'optional_fields': ['module',
                                                                  'scope.read_paths',
                                                                  'acceptance',
                                                                  'must_not_change'],
                                              'final_output_policy': 'read_only_audit_prompt'},
 'templates/METCO_TASK_BACKLOG_PROMPT_TEMPLATE.md': {'kind': 'backlog_artifact_prompt',
                                                     'required_fields': ['outcome'],
                                                     'optional_fields': ['module', 'acceptance', 'must_not_change'],
                                                     'final_output_policy': 'ordered_backlog_prompt'},
 'templates/METCO_CHANGE_IMPROVEMENT_PROMPT_TEMPLATE.md': {'kind': 'change_record_prompt',
                                                           'required_fields': ['outcome'],
                                                           'optional_fields': ['module',
                                                                               'acceptance',
                                                                               'must_not_change'],
                                                           'final_output_policy': 'controlled_change_record_prompt'}}

RUN_STATE_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'METCO Run State',
 'type': 'object',
 'required': ['request_id', 'status', 'deliverable', 'execution_shape'],
 'properties': {'request_id': {'type': 'string'},
                'status': {'type': 'string',
                           'enum': ['routing', 'blocked', 'ready', 'in_progress', 'paused', 'complete', 'failed']},
                'deliverable': {'type': 'string'},
                'artifact_mode': {'type': 'string'},
                'replit_mode': {'type': 'string'},
                'skill': {'type': 'string'},
                'execution_shape': {'type': 'string', 'enum': ['bounded', 'phased']},
                'capability': {'type': 'string'},
                'missing_authority': {'type': 'array', 'items': {'type': 'string'}},
                'scope': {'type': 'object',
                          'properties': {'write_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'read_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'locked_paths': {'type': 'array', 'items': {'type': 'string'}}}},
                'decisions': {'type': 'array', 'items': {'type': 'object'}},
                'checks': {'type': 'array', 'items': {'$ref': '#/$defs/check'}},
                'phases': {'type': 'array', 'items': {'$ref': '#/$defs/phase'}}},
 '$defs': {'check': {'type': 'object',
                     'required': ['name', 'status'],
                     'properties': {'name': {'type': 'string'},
                                    'target': {'type': 'string'},
                                    'status': {'type': 'string', 'enum': ['PASSED', 'FAILED', 'NOT RUN']},
                                    'evidence': {'type': 'string'}}},
           'phase': {'type': 'object',
                     'required': ['id', 'status', 'outcome'],
                     'properties': {'id': {'type': 'string'},
                                    'status': {'type': 'string',
                                               'enum': ['planned', 'ready', 'blocked', 'complete', 'failed']},
                                    'outcome': {'type': 'string'},
                                    'write_paths': {'type': 'array', 'items': {'type': 'string'}},
                                    'verification_gate': {'type': 'array', 'items': {'type': 'string'}},
                                    'rollback_boundary': {'type': 'string'},
                                    'handoff': {'$ref': '#/$defs/handoff'}}},
           'handoff': {'type': 'object',
                       'required': ['phase_id', 'completed', 'checks'],
                       'properties': {'phase_id': {'type': 'string'},
                                      'completed': {'type': 'boolean'},
                                      'files_changed': {'type': 'array', 'items': {'type': 'string'}},
                                      'checks': {'type': 'array', 'items': {'$ref': '#/$defs/check'}},
                                      'next_phase_ready': {'type': 'boolean'},
                                      'blockers': {'type': 'array', 'items': {'type': 'string'}}}}}}

REPORT_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'METCO Parsed Replit Report',
 'type': 'object',
 'required': ['outcome', 'checks', 'files_changed', 'residual_risk'],
 'properties': {'outcome': {'type': 'string'},
                'acceptance_status': {'type': 'string'},
                'files_changed': {'type': 'array', 'items': {'type': 'string'}},
                'checks': {'type': 'array',
                           'items': {'type': 'object',
                                     'required': ['status', 'text'],
                                     'properties': {'status': {'type': 'string',
                                                               'enum': ['PASSED', 'FAILED', 'NOT RUN']},
                                                    'text': {'type': 'string'}}}},
                'hitl_decisions': {'type': 'array', 'items': {'type': 'string'}},
                'blockers': {'type': 'array', 'items': {'type': 'string'}},
                'residual_risk': {'type': 'array', 'items': {'type': 'string'}}}}

GATES = {'version': '6',
 'required_before': ['edit', 'phase', 'final_report'],
 'gates': {'scope_gate': {'stop_if': ['missing_write_scope', 'missing_read_scope', 'owner_or_path_unknown']},
           'protected_path_gate': {'stop_if': ['protected_path_requested', 'path_may_resolve_to_protected_content']},
           'capability_gate': {'stop_if': ['risky_capability_without_explicit_authorization',
                                           'schema_migration_without_safe_environment',
                                           'data_seeding_without_idempotency',
                                           'package_config_without_exact_authorization',
                                           'destructive_cleanup_without_recovery_plan']},
           'hitl_gate': {'stop_if': ['unknown_next_step_after_bounded_inspection',
                                     'two_materially_correct_choices_without_governing_winner',
                                     'agent_made_decision_would_expand_scope',
                                     'invented_business_rule_required',
                                     'invented_permission_rule_required',
                                     'invented_data_rule_required',
                                     'invented_api_contract_required'],
                         'required_output_when_blocked': ['HITL decision required',
                                                          'HITL-ID',
                                                          'blocked_check',
                                                          'smallest_required_decision',
                                                          'evidence_checked',
                                                          'options',
                                                          'exact_resume_point',
                                                          'required_DECIDE_reply']},
           'verification_gate': {'stop_if': ['no_safe_verification_path',
                                             'verification_requires_production_or_unknown_external_system',
                                             'verification_requires_package_or_config_change']},
           'final_report_gate': {'required_sections': ['HITL Gate Result',
                                                       'Files Changed',
                                                       'Checks',
                                                       'Protected Path Compliance',
                                                       'Residual Risk']}}}

CONTRACTS = {

    'manifests/kit.manifest.json': KIT_MANIFEST,

    'manifests/routing.manifest.json': ROUTING_MANIFEST,

    'manifests/capability-gates.json': CAPABILITY_GATES,

    'manifests/protected-paths.json': PROTECTED_PATHS,

    'manifests/hitl.schema.json': HITL_SCHEMA,

    'manifests/request.schema.json': REQUEST_SCHEMA,

    'manifests/distributions.json': DISTRIBUTIONS,

    'manifests/profiles.json': PROFILES,

    'manifests/template-metadata.json': TEMPLATE_METADATA,

    'manifests/run-state.schema.json': RUN_STATE_SCHEMA,

    'manifests/report.schema.json': REPORT_SCHEMA,

    'manifests/gates.json': GATES,

}
