# Generated fixtures (OpsGate). Edit this file instead of standalone JSON fixtures.

ROUTING_FIXTURES = [{'path': 'fixtures/routing/business-request.json',
  'data': {'request': {'id': 'REQ-FIXTURE-BUSINESS-001',
                       'deliverable': 'business_file',
                       'outcome': 'Create a business file for the Roles module, including actors, scope, rules, '
                                  'outcomes, and open questions.',
                       'module': 'Roles'},
           'expected': {'deliverable': 'business_file',
                        'artifact_mode': 'BUSINESS_DEFINITION',
                        'execution_shape': 'bounded'}}},
 {'path': 'fixtures/routing/form-auth-task.json',
  'data': {'request': {'id': 'REQ-FIXTURE-FORM-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Add role-based validation to the vendor approval form and keep existing API '
                                  'contracts unchanged.',
                       'module': 'Vendor approvals',
                       'scope': {'write_paths': ['src/features/vendor-approvals/**']},
                       'must_not_change': ['API contracts', 'schema']},
           'expected': {'replit_mode': 'AUTH_PERMISSION_IMPLEMENTATION',
                        'skill': 'auth-permission-workflow',
                        'execution_shape': 'phased',
                        'blocked': False}}},
 {'path': 'fixtures/routing/frontend-task.json',
  'data': {'request': {'id': 'REQ-FIXTURE-FRONTEND-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Improve the React vendor approval page loading, empty, error, and success states '
                                  'without changing API contracts.',
                       'module': 'Vendor approvals',
                       'scope': {'write_paths': ['src/features/vendor-approvals/**']},
                       'must_not_change': ['API response shape', 'permissions']},
           'expected': {'deliverable': 'replit_prompt',
                        'artifact_mode': 'REPLIT_PROMPT_BUILD',
                        'replit_mode': 'FRONTEND_IMPLEMENTATION',
                        'skill': 'frontend-development',
                        'execution_shape': 'bounded',
                        'blocked': False}}},
 {'path': 'fixtures/routing/instruction-maintenance.json',
  'data': {'request': {'id': 'REQ-FIXTURE-INSTRUCTIONS-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Update replit.md and ai instructions to add a new safe verification workflow.',
                       'module': 'Instructions',
                       'scope': {'write_paths': ['replit.md', 'ai/**', '.agents/skills/**']}},
           'expected': {'replit_mode': 'INSTRUCTION_SYSTEM_MAINTENANCE',
                        'skill': 'instruction-maintenance',
                        'blocked': True}}},
 {'path': 'fixtures/routing/migration-task-missing-auth.json',
  'data': {'request': {'id': 'REQ-FIXTURE-MIGRATION-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Add a database schema migration and backfill for vendor approval status history.',
                       'module': 'Vendor approvals',
                       'scope': {'write_paths': ['server/src/**']}},
           'expected': {'replit_mode': 'DATABASE_SCHEMA_EVOLUTION',
                        'skill': 'database-schema-migration',
                        'execution_shape': 'phased',
                        'blocked': True,
                        'missing_authority_contains': ['safe_non_production_environment',
                                                       'rollback_plan',
                                                       'approved_target_mapping']}}},
 {'path': 'fixtures/routing/package-config-blocked.json',
  'data': {'request': {'id': 'REQ-FIXTURE-CONFIG-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Install a new package and change build configuration for the frontend app.',
                       'module': 'Frontend platform',
                       'scope': {'write_paths': ['package.json', 'vite.config.ts']},
                       'authorizations': {'package_config_environment_deployment': {'authorized': False,
                                                                                    'evidence': []}}},
           'expected': {'blocked': True, 'execution_shape': 'bounded'}}},
 {'path': 'fixtures/routing/phased-fullstack-task.json',
  'data': {'request': {'id': 'REQ-FIXTURE-FULLSTACK-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Implement a frontend and backend vendor approval workflow that changes permissions '
                                  'and public contract behavior.',
                       'module': 'Vendor approvals',
                       'scope': {'write_paths': ['src/features/vendor-approvals/**',
                                                 'server/src/vendor-approvals/**']}},
           'expected': {'replit_mode': 'AUTH_PERMISSION_IMPLEMENTATION',
                        'skill': 'auth-permission-workflow',
                        'execution_shape': 'phased'}}},
 {'path': 'fixtures/routing/read-only-audit.json',
  'data': {'request': {'id': 'REQ-FIXTURE-AUDIT-001',
                       'deliverable': 'audit',
                       'outcome': 'Audit the Roles module against the approved business file without changing code.',
                       'module': 'Roles',
                       'scope': {'read_paths': ['src/features/roles/**']}},
           'expected': {'deliverable': 'audit', 'artifact_mode': 'EVIDENCE_AUDIT', 'execution_shape': 'bounded'}}},
 {'path': 'fixtures/routing/specification-request.json',
  # Regression coverage for compile_artifact_prompt's "specification" body - previously
  # untested by any fixture (only replit_prompt/business_file/audit deliverables had one),
  # despite specification being one of the six artifact routes.
  'data': {'request': {'id': 'REQ-FIXTURE-SPEC-001',
                       'deliverable': 'specification',
                       'outcome': 'Write an implementation-ready specification documenting the API contracts and '
                                  'state transitions for the Suppliers module.',
                       'module': 'Suppliers'},
           'expected': {'deliverable': 'specification',
                        'artifact_mode': 'IMPLEMENTATION_SPECIFICATION',
                        'execution_shape': 'bounded'}}},
 {'path': 'fixtures/routing/specification-bare-delta-word.json',
  # Regression coverage for a real false-positive: is_delta_spec used to match the bare word
  # "delta" anywhere in module/outcome text, so a request about an unrelated module literally
  # named "Delta" (or containing a phrase like "delta-neutral") wrongly got the delta-spec
  # compiled body instead of the ordinary full-spec one. Tightened to require the two-word
  # phrase "delta spec"/"delta specification" - this fixture's module name alone must not
  # trigger it.
  'data': {'request': {'id': 'REQ-FIXTURE-SPEC-BARE-DELTA-001',
                       'deliverable': 'specification',
                       'module': 'Delta',
                       'outcome': 'Write a specification for the Delta module reporting pipeline.'},
           'expected': {'deliverable': 'specification',
                        'artifact_mode': 'IMPLEMENTATION_SPECIFICATION',
                        'execution_shape': 'bounded'}}},
 {'path': 'fixtures/routing/specification-delta-request.json',
  # Regression coverage for the delta-spec compiled body - locks in that a request whose
  # module/outcome mentions "delta" gets the Summary-of-Changes/D-*/Acceptance-Criteria-Addendum
  # structure real delta specs use, not the generic full-spec body.
  'data': {'request': {'id': 'REQ-FIXTURE-SPEC-DELTA-001',
                       'deliverable': 'specification',
                       'module': 'Suppliers',
                       'outcome': 'Produce a delta specification documenting what changed in the Suppliers module '
                                  'business rules since the last approved revision.'},
           'expected': {'deliverable': 'specification',
                        'artifact_mode': 'IMPLEMENTATION_SPECIFICATION',
                        'execution_shape': 'bounded'}}},
 {'path': 'fixtures/routing/open-capability-explicit-false.json',
  # Regression coverage for a real check_capabilities_result/route_request divergence: an
  # explicit authorized:false on a capability whose gate default is NOT "blocked" (here
  # ordinary_application_change, default allowed_when_scoped) must not block the request either
  # way - only a capability whose own gate defaults to "blocked" requires explicit
  # authorized:true. Before the fix, route_request (and therefore preflight) blocked this while
  # check_capabilities_result did not, so the same request got two different verdicts.
  'data': {'request': {'id': 'REQ-FIXTURE-OPEN-CAP-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Fix a small display bug in the login form.',
                       'module': 'Login',
                       'scope': {'write_paths': ['src/features/login/**']},
                       'authorizations': {'ordinary_application_change': {'authorized': False}}},
           'expected': {'blocked': False, 'execution_shape': 'bounded'}}},
 {'path': 'fixtures/routing/malformed-authorization-value.json',
  # Regression coverage for a real crash: capability_authorized() used to call .get() on
  # whatever an authorizations entry held without checking it was actually a dict first - a
  # caller sending `{"schema_migration_backfill": true}` (a bare boolean, an easy typo for
  # `{"authorized": true}`) raised an unhandled AttributeError from route_request/
  # check_capabilities_result/preflight, since neither this data nor the request as a whole is
  # validated against REQUEST_SCHEMA before reaching routing. Must fail closed (blocked/not
  # authorized), never crash.
  'data': {'request': {'id': 'REQ-FIXTURE-MALFORMED-AUTH-001',
                       'deliverable': 'replit_prompt',
                       'outcome': 'Run a schema migration to add the new column.',
                       'module': 'Schema',
                       'scope': {'write_paths': ['x']},
                       'authorizations': {'schema_migration_backfill': True}},
           'expected': {'blocked': True, 'execution_shape': 'phased'}}}]

HITL_FIXTURES = [{'path': 'fixtures/hitl/case-1-missing-next-step.json',
  'data': {'id': 'HITL-vendor-approval-P1-Q1',
           'case': 1,
           'blocked_step': 'Select the next implementation target after bounded inspection found no existing owner.',
           'question': 'Which approved owner should receive the new vendor approval workflow?',
           'evidence_checked': ['Approved scope', 'Named frontend feature folder', 'Direct route registration'],
           'options': ['A. Existing vendor approvals feature folder - resume inside '
                       'src/features/vendor-approvals only',
                       'B. Stop implementation and return a scope request - no files changed until an owner is named'],
           'exact_resume_point': 'Phase 1 owner selection before editing',
           'resume_reply': 'DECIDE HITL-vendor-approval-P1-Q1: use src/features/vendor-approvals as '
                           'the owner.'}},
 {'path': 'fixtures/hitl/case-2-two-valid-options.json',
  'data': {'id': 'HITL-vendor-approval-P1-Q2',
           'case': 2,
           'blocked_step': 'Choose between two existing table patterns.',
           'question': 'Should this module reuse the compact operations table or the workflow review table?',
           'evidence_checked': ['Existing table components',
                                'Current design system patterns',
                                'Module workflow evidence'],
           'options': ['A. Compact operations table - resume with the denser operations pattern',
                       'B. Workflow review table - resume with the clearer approval-state pattern'],
           'exact_resume_point': 'Phase 1 table-pattern selection before component changes',
           'resume_reply': 'DECIDE HITL-vendor-approval-P1-Q2: use the workflow review table for approval-state '
                           'clarity.'}},
 {'path': 'fixtures/hitl/case-3-scope-expansion.json',
  'data': {'id': 'HITL-vendor-approval-P2-Q1',
           'case': 3,
           'blocked_step': 'Proceeding would require expanding scope to generated API contracts.',
           'question': 'Do you authorize changing the generated client contract files for this phase?',
           'evidence_checked': ['Approved phase write paths',
                                'Generated contract dependency',
                                'Locked generated-file policy'],
           'options': ['A. Stay inside current phase scope - preserve generated contracts and adapt only approved '
                       'files',
                       'B. Authorize generated contract change - expand scope only to the named generated contract '
                       'files with compatibility checks'],
           'exact_resume_point': 'Phase 2 contract boundary decision before generated-file access',
           'resume_reply': 'DECIDE HITL-vendor-approval-P2-Q1: do not change generated contracts; preserve current '
                           'contract shape.'}}]

READY_PHASED_STATE = {'request_id': 'REQ-FIXTURE-PHASED-READY-001',
 'status': 'ready',
 'deliverable': 'replit_prompt',
 'artifact_mode': 'REPLIT_PROMPT_BUILD',
 'replit_mode': 'FULL_STACK_IMPLEMENTATION',
 'skill': 'full-stack-feature',
 'execution_shape': 'phased',
 'capability': 'ordinary_application_change',
 'missing_authority': [],
 'scope': {'write_paths': ['src/features/vendor-approvals/**',
                           'server/src/vendor-approvals/**'],
           'read_paths': []},
 'decisions': [],
 'checks': [],
 'phases': [{'id': 'PHASE-0',
             'status': 'complete',
             'outcome': 'Discovery and contract proof',
             'write_paths': [],
             'verification_gate': ['Owners and contracts identified'],
             'rollback_boundary': 'No writes'},
            {'id': 'PHASE-1',
             'status': 'ready',
             'outcome': 'Implement the bounded backend foundation for vendor approval workflow',
             'write_paths': ['server/src/vendor-approvals/**'],
             'verification_gate': ['Backend success and permission-denial checks are reported'],
             'rollback_boundary': 'Backend vendor approval files only'}]}

PARSED_SAMPLE_REPORT = {'outcome': 'Vendor approval loading and error states were updated.',
 'acceptance_status': 'PASSED: Loading, empty, error, retry, and success states are represented.',
 'files_changed': ['src/features/vendor-approvals/VendorApprovalPage.tsx',
                   'src/features/vendor-approvals/useVendorApprovals.ts'],
 'checks': [{'status': 'PASSED', 'text': 'targeted component test for loading and error states'},
            {'status': 'NOT RUN', 'text': 'browser viewport check, local preview unavailable'}],
 'hitl_decisions': [],
 'blockers': [],
 'residual_risk': ['Manual responsive verification still needed.']}

GOLD_STANDARD_BOUNDED_FRONTEND_REQUEST = {'id': 'REQ-GOLD-FRONTEND-001',
 'deliverable': 'replit_prompt',
 'outcome': 'Improve the vendor approval page loading, empty, error, retry, and success states without changing API '
            'contracts.',
 'module': 'Vendor approvals',
 'scope': {'write_paths': ['src/features/vendor-approvals/**'],
           'read_paths': ['src/features/vendor-approvals/**']},
 'acceptance': ['Loading, empty, error, retry, and success states are visible and role-safe.',
                'Existing API contracts and permission behavior remain unchanged.',
                'Targeted checks are reported as PASSED, FAILED, or NOT RUN.'],
 'must_not_change': ['API response shape', 'Backend authorization', 'Schema or migrations']}

GOLD_STANDARD_PHASED_MIGRATION_REQUEST = {'id': 'REQ-GOLD-MIGRATION-001',
 'deliverable': 'replit_prompt',
 'outcome': 'Add a non-production migration and backfill for vendor approval status history.',
 'module': 'Vendor approvals',
 'scope': {'write_paths': ['server/src/vendor-approvals/**'],
           'read_paths': ['server/src/vendor-approvals/**']},
 'authorizations': {'schema_migration_backfill': {'authorized': True,
                                                  'evidence': ['Approved ERD mapping: vendor approval status history',
                                                               'Safe non-production environment confirmed',
                                                               'Rollback plan documented']}},
 'acceptance': ['Migration is additive and repeatable in a safe non-production environment.',
                'Backfill validates counts, nulls, duplicates, and tenant isolation.',
                'Cleanup is deferred to a later explicitly authorized phase.'],
 'must_not_change': ['Production data', 'Protected systems', 'Package or ORM tooling']}
