# Generated engine contracts (OpsGate). Edit this file instead of standalone JSON manifests.

ENGINE_MANIFEST = {'name': 'opsgate',
 'version': '7.0.0',
 'release_date': '2026-08-17',
 'source_version': '7',
 'purpose': 'Governance engine for AI coding agents working on Replit projects: canonical prompt/skill '
            'content with object-oriented instruction contracts, served through a hosted, multi-tenant '
            'MCP server (mcp-server/) exposing gates as live tool calls.',
 'content_root': 'content',
 'commands': {'validate': 'python3 tools/opsgate.py validate-engine',
              'test_all': 'python3 tools/opsgate.py test-all',
              'route': 'python3 tools/opsgate.py route-request <request.json>',
              'compile': 'python3 tools/opsgate.py compile-prompt <request.json>',
              'init_state': 'python3 tools/opsgate.py init-state <request.json>',
              'parse_report': 'python3 tools/opsgate.py parse-report <report.md>',
              'intake': 'python3 tools/opsgate.py intake-request "<plain language request>"',
              'next_phase': 'python3 tools/opsgate.py next-phase-prompt <run-state.json> <parsed-report.json>',
              'preflight': 'python3 tools/opsgate.py preflight <request.json>',
              'check_paths': 'python3 tools/opsgate.py check-paths <request.json>',
              'check_capabilities': 'python3 tools/opsgate.py check-capabilities <request.json>',
              'lint_prompt': 'python3 tools/opsgate.py lint-prompt <prompt.md>',
              'lint_report': 'python3 tools/opsgate.py lint-report <report.md>',
              'init_run': 'python3 tools/opsgate.py init-run <request.json>',
              'record_decision': 'python3 tools/opsgate.py record-decision <HITL-ID> <answer and exact scope>',
              'show_profile': 'python3 tools/opsgate.py show-profile [request.json] [--tenant <id>]',
              'validate_json': 'python3 tools/opsgate.py validate-json <schema-contract> <data-file>'},
 'release_acceptance': ['Replit skill metadata is valid',
                        'protected path rules remain present',
                        'HITL is limited to three cases',
                        'routing fixtures produce expected outcomes',
                        'canonical AI instruction objects expose responsibility, activation, inputs, boundaries, '
                        'workflow, and output evidence']}

ROUTING_MANIFEST = {'artifact_routes': [{'deliverable': 'business_file',
                      'mode': 'BUSINESS_DEFINITION',
                      'template': 'templates/BUSINESS_FILE_PROMPT_TEMPLATE.md',
                      'signals': ['business', 'scope', 'rules', 'outcomes', 'stakeholders', 'module audit']},
                     {'deliverable': 'specification',
                      'mode': 'IMPLEMENTATION_SPECIFICATION',
                      'template': 'templates/SPEC_FILE_PROMPT_TEMPLATE.md',
                      'signals': ['specification', 'contracts', 'states', 'data', 'delta spec']},
                     {'deliverable': 'audit',
                      'mode': 'EVIDENCE_AUDIT',
                      'template': 'templates/AUDIT_PROMPT_TEMPLATE.md',
                      'signals': ['audit', 'review', 'findings', 'compliance', 'risk']},
                     {'deliverable': 'task_backlog',
                      'mode': 'DELIVERY_BACKLOG',
                      'template': 'templates/TASK_BACKLOG_PROMPT_TEMPLATE.md',
                      'signals': ['backlog', 'tasks', 'delivery plan']},
                     {'deliverable': 'change_record',
                      'mode': 'CHANGE_CONTROL',
                      'template': 'templates/CHANGE_IMPROVEMENT_PROMPT_TEMPLATE.md',
                      'signals': ['change', 'improvement', 'amendment']},
                     {'deliverable': 'replit_prompt',
                      'mode': 'REPLIT_PROMPT_BUILD',
                      'template': 'templates/REPLIT_TASK_TEMPLATE.md',
                      'signals': ['implement', 'fix', 'build', 'replit prompt']}],
 'replit_routes': [{'mode': 'AUTH_PERMISSION_IMPLEMENTATION',
                    'skill': 'auth-permission-workflow',
                    'signals': ['auth',
                                'permission',
                                'permissions',
                                'changes permissions',
                                'role',
                                'role-based',
                                'tenant',
                                'object scope',
                                'sensitive field',
                                'authorization'],
                    'references': ['ai/backend.md',
                                   'ai/database.md',
                                   'ai/security.md',
                                   'ai/frontend.md',
                                   'ai/testing.md']},
                   {'mode': 'DATABASE_SCHEMA_EVOLUTION',
                    'skill': 'database-schema-migration',
                    'signals': ['schema', 'migration', 'backfill', 'mapping', 'index'],
                    'capability': 'schema_migration_backfill',
                    'force_phased': True,
                    'references': ['ai/database.md',
                                   'ai/backend.md',
                                   'ai/security.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'NONPRODUCTION_DATA_SEEDING',
                    'skill': 'data-seeding',
                    'signals': ['seed', 'seeding', 'demo data', 'test data'],
                    'capability': 'data_seeding',
                    'force_phased': True,
                    'references': ['ai/database.md',
                                   'ai/backend.md',
                                   'ai/security.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'FORM_WORKFLOW_IMPLEMENTATION',
                    'skill': 'form-workflow',
                    'signals': ['form', 'validation', 'save', 'cancel', 'mutation'],
                    'references': ['ai/frontend.md', 'ai/ui-ux.md', 'ai/testing.md']},
                   {'mode': 'TABLE_REPORTING_IMPLEMENTATION',
                    'skill': 'table-reporting-workflow',
                    'signals': ['table', 'filter', 'sort', 'pagination', 'report', 'dashboard'],
                    'references': ['ai/frontend.md',
                                   'ai/ui-ux.md',
                                   'ai/testing.md',
                                   'ai/backend.md',
                                   'ai/database.md',
                                   'ai/security.md']},
                   {'mode': 'FRONTEND_ARCHITECTURE_REFACTOR',
                    'skill': 'frontend-architecture-refactor',
                    'signals': ['refactor', 'consolidate', 'decompose', 'duplicate component'],
                    'capability': 'broad_architecture_refactor',
                    'force_phased': True,
                    'references': ['ai/frontend.md',
                                   'ai/refactoring.md',
                                   'ai/ui-ux.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'PERFORMANCE_OPTIMIZATION',
                    'skill': 'performance-optimization',
                    'signals': ['performance', 'slow', 'latency', 'render', 'n+1', 'payload'],
                    'references': ['ai/testing.md',
                                   'ai/frontend.md',
                                   'ai/backend.md',
                                   'ai/database.md']},
                   {'mode': 'UI_UX_REVIEW',
                    'skill': 'ui-ux-review',
                    'signals': ['ui', 'ux', 'responsive', 'accessibility', 'visual'],
                    'references': ['ai/ui-ux.md', 'ai/testing.md']},
                   {'mode': 'BUG_DIAGNOSIS',
                    'skill': 'bug-diagnosis',
                    'signals': ['bug', 'diagnose', 'root cause', 'reproduce'],
                    'references': ['ai/testing.md']},
                   {'mode': 'FULL_STACK_IMPLEMENTATION',
                    'skill': 'full-stack-feature',
                    'signals': ['frontend and backend', 'full stack', 'api and ui'],
                    'force_phased_when_risky': True,
                    'references': ['ai/backend.md',
                                   'ai/database.md',
                                   'ai/security.md',
                                   'ai/frontend.md',
                                   'ai/ui-ux.md',
                                   'ai/testing.md',
                                   'ai/agents.md']},
                   {'mode': 'API_IMPLEMENTATION',
                    'skill': 'api-server-development',
                    'signals': ['api', 'endpoint', 'service', 'repository', 'backend'],
                    'references': ['ai/backend.md', 'ai/testing.md']},
                   {'mode': 'FRONTEND_IMPLEMENTATION',
                    'skill': 'frontend-development',
                    'signals': ['frontend', 'react', 'component', 'page', 'hook', 'client'],
                    'references': ['ai/frontend.md', 'ai/ui-ux.md', 'ai/testing.md']},
                   {'mode': 'SAFE_VERIFICATION',
                    'skill': 'safe-verification',
                    'signals': ['verify', 'qa', 'regression', 'read-only'],
                    'references': ['ai/testing.md']},
                   {'mode': 'INSTRUCTION_SYSTEM_MAINTENANCE',
                    'skill': 'instruction-maintenance',
                    'signals': ['replit.md', 'ai instructions', '.agents/skills', 'instruction'],
                    'capability': 'instruction_maintenance',
                    'references': ['ai/maintenance.md']}],
 'phased_triggers': ['schema',
                     'migration',
                     'backfill',
                     'seeding',
                     'authentication',
                     'tenant',
                     'sensitive data',
                     'public contract',
                     'broad refactor',
                     'destructive cleanup',
                     'multiple independently reversible surfaces']}

CAPABILITY_GATES = {'ordinary_application_change': {'default': 'allowed_when_scoped',
                                 'requires': ['observable_outcome', 'exact_scope_inside_normal_write_paths']},
 'audit_or_diagnosis_without_fixes': {'default': 'read_only', 'requires': ['approved_inspection_scope']},
 'broad_architecture_refactor': {'default': 'blocked',
                                 'requires': ['explicit_broad_outcome',
                                              'named_approved_source_tree',
                                              'preserved_contracts',
                                              'phased_rollback']},
 'instruction_maintenance': {'default': 'blocked',
                             'requires': ['explicit_instruction_change_request', 'exact_instruction_paths']},
 'schema_migration_backfill': {'default': 'blocked',
                               'requires': ['explicit_schema_or_migration_request',
                                            'approved_target_mapping',
                                            'named_established_paths',
                                            'safe_non_production_environment',
                                            'rollback_plan']},
 'data_seeding': {'default': 'blocked',
                  'requires': ['explicit_seeding_request',
                               'named_established_seed_paths',
                               'safe_non_production_environment',
                               'approved_profiles_and_scale',
                               'idempotency']},
 'contract_change_or_destructive_cleanup': {'default': 'blocked',
                                            'requires': ['explicit_changed_boundary',
                                                         'consumer_evidence',
                                                         'compatibility_plan',
                                                         'recovery_plan']},
 'package_config_environment_deployment': {'default': 'blocked',
                                           'requires': ['exact_explicit_authorization',
                                                        'task_specific_safety_prerequisites']}}

# Protections every tenant gets regardless of its own frontend/backend roots - universal
# engineering risks (VCS internals, secrets files, dependency trees, CI, agent memory), not
# anything specific to one project. Every tenant (see opsgate_tenants.protected_paths_for_tenant())
# gets this baseline merged in, so a brand-new tenant with no extra_never_access still gets
# real protection instead of an empty or missing protected-path list.
_UNIVERSAL_NEVER_ACCESS = ['.git/**', '.env', '.env.*', 'node_modules/**', '.github/workflows/**', '.claude/**', '.agents/memory/**']
# Locked-by-default categories are already project-agnostic (packages, lockfiles, schema,
# secrets, etc. are universal engineering categories, not METCO-specific paths), so both
# profiles below share the exact same list rather than each declaring their own copy.
_UNIVERSAL_LOCKED_BY_DEFAULT = ['packages',
                               'lockfiles',
                               'dependencies',
                               'workspace_config',
                               'build_lint_format_config',
                               '.replit',
                               'environment',
                               'secrets',
                               'deployment',
                               'infrastructure',
                               'generated_contracts',
                               'schema',
                               'migrations',
                               'seeds',
                               '.agents/memory/**',
                               'instructions',
                               'unrelated_docs']

HITL_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'HITL Decision',
 'type': 'object',
 'required': ['id',
              'case',
              'blocked_step',
              'question',
              'evidence_checked',
              'options',
              'exact_resume_point',
              'resume_reply'],
 'properties': {'id': {'type': 'string', 'pattern': '^HITL-[A-Za-z0-9-]+(-P[0-9]+)?-Q[0-9]+$'},
                'case': {'type': 'integer', 'enum': [1, 2, 3]},
                'blocked_step': {'type': 'string', 'minLength': 1},
                'question': {'type': 'string', 'minLength': 1},
                'evidence_checked': {'type': 'array', 'items': {'type': 'string'}, 'minItems': 1},
                'options': {'type': 'array', 'items': {'type': 'string', 'minLength': 1}, 'minItems': 2, 'maxItems': 4},
                'exact_resume_point': {'type': 'string', 'minLength': 1},
                'resume_reply': {'type': 'string', 'pattern': '^DECIDE HITL-[A-Za-z0-9-]+(-P[0-9]+)?-Q[0-9]+: .+'}}}

REQUEST_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'Engine Request',
 'type': 'object',
 'required': ['id', 'outcome', 'deliverable'],
 'properties': {'id': {'type': 'string'},
                'outcome': {'type': 'string'},
                'deliverable': {'type': 'string',
                                'enum': ['business_file',
                                         'specification',
                                         'audit',
                                         'task_backlog',
                                         'change_record',
                                         'replit_prompt']},
                'module': {'type': 'string'},
                'scope': {'type': 'object',
                          'properties': {'write_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'read_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'locked_paths': {'type': 'array', 'items': {'type': 'string'}}}},
                'authorizations': {'type': 'object',
                                   'additionalProperties': {'type': 'object',
                                                            'properties': {'authorized': {'type': 'boolean'},
                                                                           'evidence': {'type': 'array',
                                                                                        'items': {'type': 'string'}}}}},
                'acceptance': {'type': 'array', 'items': {'type': 'string'}},
                'must_not_change': {'type': 'array', 'items': {'type': 'string'}},
                # Optional speed-oriented fields for replit_prompt requests - all opt-in, and
                # each is a no-op when absent so existing requests compile byte-identical prompts.
                'mcp': {'type': 'object',
                       'description': 'When enabled, compile-prompt.py emits MCP tool-call instructions (opsgate_preflight/check_paths/check_capability/record_decision) for the HITL gate instead of a manual prose reasoning table, since the target project has those tools registered on /mcp.',
                       'properties': {'enabled': {'type': 'boolean'},
                                      'tool_prefix': {'type': 'string', 'description': 'Defaults to "opsgate_" - override only if the target server registered the engine\'s tools under a different prefix.'}}},
                'known_context': {'type': 'object',
                                  'description': 'When any of these are set, compile-prompt.py replaces the open-ended discovery steps with a targeted verification instruction against the named items instead of telling the agent to go find them.',
                                  'properties': {'owners': {'type': 'array', 'items': {'type': 'string'}},
                                                 'callers': {'type': 'array', 'items': {'type': 'string'}},
                                                 'tests': {'type': 'array', 'items': {'type': 'string'}}}},
                'reference_scope': {'type': 'string',
                                    'enum': ['full', 'minimal'],
                                    'description': 'Defaults to "full" (unchanged behavior). "minimal" trims required_references down to only the ones whose topic keywords appear in the request text/scope, always keeping replit.md and the resolved tenant\'s business_file, if it has one.'}}}

RUN_STATE_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'Run State',
 'type': 'object',
 'required': ['request_id', 'status', 'deliverable', 'execution_shape'],
 'properties': {'request_id': {'type': 'string'},
                'status': {'type': 'string',
                           'enum': ['routing', 'blocked', 'ready', 'in_progress', 'paused', 'complete', 'failed']},
                'deliverable': {'type': 'string'},
                'artifact_mode': {'type': 'string'},
                'replit_mode': {'type': 'string'},
                'skill': {'type': 'string'},
                'execution_shape': {'type': 'string', 'enum': ['bounded', 'phased']},
                'capability': {'type': 'string'},
                'missing_authority': {'type': 'array', 'items': {'type': 'string'}},
                'scope': {'type': 'object',
                          'properties': {'write_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'read_paths': {'type': 'array', 'items': {'type': 'string'}},
                                         'locked_paths': {'type': 'array', 'items': {'type': 'string'}}}},
                'decisions': {'type': 'array', 'items': {'type': 'object'}},
                'checks': {'type': 'array', 'items': {'$ref': '#/$defs/check'}},
                'phases': {'type': 'array', 'items': {'$ref': '#/$defs/phase'}}},
 '$defs': {'check': {'type': 'object',
                     'required': ['name', 'status'],
                     'properties': {'name': {'type': 'string'},
                                    'target': {'type': 'string'},
                                    'status': {'type': 'string', 'enum': ['PASSED', 'FAILED', 'NOT RUN']},
                                    'evidence': {'type': 'string'}}},
           'phase': {'type': 'object',
                     'required': ['id', 'status', 'outcome'],
                     'properties': {'id': {'type': 'string'},
                                    'status': {'type': 'string',
                                               'enum': ['planned', 'ready', 'blocked', 'complete', 'failed']},
                                    'outcome': {'type': 'string'},
                                    'write_paths': {'type': 'array', 'items': {'type': 'string'}},
                                    'verification_gate': {'type': 'array', 'items': {'type': 'string'}},
                                    'rollback_boundary': {'type': 'string'},
                                    'handoff': {'$ref': '#/$defs/handoff'}}},
           'handoff': {'type': 'object',
                       'required': ['phase_id', 'completed', 'checks'],
                       'properties': {'phase_id': {'type': 'string'},
                                      'completed': {'type': 'boolean'},
                                      'files_changed': {'type': 'array', 'items': {'type': 'string'}},
                                      'checks': {'type': 'array', 'items': {'$ref': '#/$defs/check'}},
                                      'next_phase_ready': {'type': 'boolean'},
                                      'blockers': {'type': 'array', 'items': {'type': 'string'}}}}}}

REPORT_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema',
 'title': 'Parsed Replit Report',
 'type': 'object',
 'required': ['outcome', 'checks', 'files_changed', 'residual_risk'],
 'properties': {'outcome': {'type': 'string'},
                'acceptance_status': {'type': 'string'},
                'files_changed': {'type': 'array', 'items': {'type': 'string'}},
                'checks': {'type': 'array',
                           'items': {'type': 'object',
                                     'required': ['status', 'text'],
                                     'properties': {'status': {'type': 'string',
                                                               'enum': ['PASSED', 'FAILED', 'NOT RUN']},
                                                    'text': {'type': 'string'}}}},
                'hitl_decisions': {'type': 'array', 'items': {'type': 'string'}},
                'blockers': {'type': 'array', 'items': {'type': 'string'}},
                'residual_risk': {'type': 'array', 'items': {'type': 'string'}}}}

GATES = {'version': '7',
 'required_before': ['edit', 'phase', 'final_report'],
 'gates': {'scope_gate': {'stop_if': ['missing_write_scope', 'missing_read_scope', 'owner_or_path_unknown']},
           'protected_path_gate': {'stop_if': ['protected_path_requested', 'path_may_resolve_to_protected_content']},
           'capability_gate': {'stop_if': ['risky_capability_without_explicit_authorization',
                                           'schema_migration_without_safe_environment',
                                           'data_seeding_without_idempotency',
                                           'package_config_without_exact_authorization',
                                           'destructive_cleanup_without_recovery_plan']},
           'hitl_gate': {'stop_if': ['unknown_next_step_after_bounded_inspection',
                                     'two_materially_correct_choices_without_governing_winner',
                                     'agent_made_decision_would_expand_scope',
                                     'invented_business_rule_required',
                                     'invented_permission_rule_required',
                                     'invented_data_rule_required',
                                     'invented_api_contract_required'],
                         'required_output_when_blocked': ['HITL decision required',
                                                          'HITL-ID',
                                                          'blocked_check',
                                                          'smallest_required_decision',
                                                          'evidence_checked',
                                                          'options',
                                                          'exact_resume_point',
                                                          'required_DECIDE_reply']},
           'verification_gate': {'stop_if': ['no_safe_verification_path',
                                             'verification_requires_production_or_unknown_external_system',
                                             'verification_requires_package_or_config_change']},
           'final_report_gate': {'required_sections': ['HITL Gate Result',
                                                       'Files Changed',
                                                       'Checks',
                                                       'Protected Path Compliance',
                                                       'Residual Risk']}}}

CONTRACTS = {

    'manifests/engine.manifest.json': ENGINE_MANIFEST,

    'manifests/routing.manifest.json': ROUTING_MANIFEST,

    'manifests/capability-gates.json': CAPABILITY_GATES,

    'manifests/hitl.schema.json': HITL_SCHEMA,

    'manifests/request.schema.json': REQUEST_SCHEMA,

    'manifests/run-state.schema.json': RUN_STATE_SCHEMA,

    'manifests/report.schema.json': REPORT_SCHEMA,

    'manifests/gates.json': GATES,

}
